import { mkdir, writeFile } from "node:fs/promises";
import { basename, join } from "node:path";
import type { AnalyzedQuery, GenerateResult, QueryMode, ResolvedConfig } from "./types.js";

export async function writeEffectModule(
  config: ResolvedConfig,
  queries: readonly AnalyzedQuery[],
): Promise<GenerateResult> {
  await mkdir(config.outDir, { recursive: true });

  const outFile = join(config.outDir, "index.ts");
  await writeFile(outFile, renderEffectModule(queries));

  return {
    configFile: config.configFile,
    outFile,
    queryCount: queries.length,
  };
}

export function renderEffectModule(queries: readonly AnalyzedQuery[]): string {
  const blocks = queries.map(renderQueryBlock).join("\n\n");

  return [
    "/* eslint-disable */",
    "// Generated by effql. Do not edit by hand.",
    'import { Effect, Schema } from "effect";',
    'import { SqlClient, SqlSchema } from "@effect/sql";',
    "",
    blocks,
    "",
  ].join("\n");
}

function renderQueryBlock(query: AnalyzedQuery): string {
  const paramsSchemaName = `${query.name}ParamsSchema`;
  const paramsTypeName = `${query.name}Params`;
  const resultSchemaName = `${query.name}ResultSchema`;
  const resultTypeName = `${query.name}Result`;
  const sqlName = `${toCamelCase(query.name)}Sql`;
  const fnName = toCamelCase(query.name);
  const bindings = query.params.map((param) => `request${renderPropertyAccess(param.name)}`);

  const lines = [
    renderQueryDoc(query),
    `export const ${paramsSchemaName} = Schema.Struct(${renderSchemaShape(query.params)});`,
    `export type ${paramsTypeName} = Schema.Schema.Type<typeof ${paramsSchemaName}>;`,
  ];

  if (query.mode !== "exec") {
    lines.push(
      `export const ${resultSchemaName} = Schema.Struct(${renderSchemaShape(query.fields)});`,
      `export type ${resultTypeName} = Schema.Schema.Type<typeof ${resultSchemaName}>;`,
    );
  }

  lines.push(`export const ${sqlName} = ${quoteTemplateString(query.normalizedSql)};`);

  const executor = `Effect.flatMap(SqlClient.SqlClient, (sql) =>\n    sql.unsafe(${sqlName}${bindings.length > 0 ? `, [${bindings.join(", ")}]` : ""})\n  )`;

  if (query.mode === "exec") {
    lines.push(
      `export const ${fnName} = SqlSchema.void({`,
      `  Request: ${paramsSchemaName},`,
      `  execute: (request) => ${executor},`,
      `});`,
    );

    return lines.join("\n");
  }

  lines.push(
    `export const ${fnName} = SqlSchema.${schemaFactory(query.mode)}({`,
    `  Request: ${paramsSchemaName},`,
    `  Result: ${resultSchemaName},`,
    `  execute: (request) => ${executor},`,
    `});`,
  );

  return lines.join("\n");
}

function renderQueryDoc(query: AnalyzedQuery): string {
  return [
    "/**",
    ` * Query: ${query.name}`,
    ` * Source: ${basename(query.sourceFile)}`,
    " *",
    " * ```sql",
    ...query.sql.split("\n").map((line) => ` * ${line}`),
    " * ```",
    " */",
  ].join("\n");
}

function schemaFactory(mode: QueryMode): string {
  switch (mode) {
    case "one":
      return "single";
    case "maybeOne":
      return "findOne";
    case "many":
      return "findAll";
    case "exec":
      return "void";
  }
}

function renderSchemaShape(fields: ReadonlyArray<{ name: string; schema: string }>): string {
  if (fields.length === 0) {
    return "{}";
  }

  return `{
${fields.map((field) => `  ${renderObjectKey(field.name)}: ${field.schema},`).join("\n")}
}`;
}

function renderPropertyAccess(name: string): string {
  return isIdentifier(name) ? `.${name}` : `[${JSON.stringify(name)}]`;
}

function renderObjectKey(name: string): string {
  return isIdentifier(name) ? name : JSON.stringify(name);
}

function isIdentifier(value: string): boolean {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(value);
}

function toCamelCase(value: string): string {
  return value.length === 0 ? value : value[0].toLowerCase() + value.slice(1);
}

function quoteTemplateString(sql: string): string {
  return `String.raw\`${sql.replaceAll("`", "\\`").replaceAll("${", "\\${")}\``;
}
